{
  "Heading": {
    "Banned": "Banned",
    "Warning": "Warning",
    "Suspended1Day": "Suspended for 1 day",
    "Suspended3Days": "Suspended for 3 days",
    "Suspended7Days": "Suspended for 7 days",
    "Suspended14Days": "Suspended for 14 days",
    "Suspended": "Suspended",
    "WhatHappened": "What happened",
    "WhyThisHappened": "Why this happened",
    "RecentActivity": "Recent activity we reviewed",
    "LatestActivity": "Latest activity we reviewed",
    "FollowTheRules": "Remember to follow the rules",
    "ViolationsAddUp": "Rule violations add up"
  },
  "Reasons": {
    "BanEvasion": "Ban Evasion",
    "Other": "Other",
    "Harassment": "Harassment",
    "ExtortionThreats": "Extortion and Threats",
    "Spam": "Spam",
    "ScamsDeceptive": "Scams and Deceptive Practices",
    "DiscriminationHate": "Discrimination or Hate",
    "SexualAdult": "Sexual or Adult Content",
    "MisusingSystems": "Misusing Boiby Systems",
    "Copyright": "Copyright Violation",
    "ChildSafety": "Child Safety",
    "ExtremistContent": "Extremist Content",
    "ViolentGore": "Violent Content and Gore",
    "UndisclosedAds": "Undisclosed Advertisement",
    "DisruptiveAudio": "Disruptive Audio",
    "HarmfulDangerous": "Harmful or Dangerous Activities",
    "Misinformation": "Misinformation",
    "Dating": "Dating",
    "IllegalRegulated": "Illegal or Regulated Content",
    "SensitiveEvents": "Mocking Real-World Sensitive Events",
    "Chargebacks": "Chargebacks",
    "RepeatedRefunds": "Repeated Refund Requests",
    "PaymentAbuse": "Payment Abuse"
  },
  "Presets": {
    "BanEvasion": "This account is linked to an account that was banned due to severe violations of our Community Standards.",
    "Harassment": "Boiby does not permit bullying or targeted harassment towards other users.",
    "Spam": "Boiby does not allow repetitive, unwanted, and/or automated high-volume messaging or posting.",
    "HateSpeech": "Any content or behaviour that promotes hate speech or discriminatory content is not permitted on Boiby.",
    "SexualContent": "Boiby prohibits users from uploading highly suggestive or sexually explicit content.",
    "Scams": "Boiby prohibits any attempts to deceive users for financial gain or personal information."
  },
  "Descriptions": {
    "BrokeRulesBanned": "We banned your Boiby account because of serious or repeated rule violations.",
    "BrokeRulesBannedV2": "We permanently banned your Boiby account due to serious or repeated rule violations.",
    "GenericDescription": "Your recent behaviour broke Boiby's rules.",
    "SpecificDescription": "Your recent behaviour broke Boiby's rules about: {{reason}}.",
    "SpecificTypeDescriptionPlural": "One of your {{type}}s broke Boiby's rules about: {{reason}}.",
    "SpecificTypeDescription": "Your {{type}} broke Boiby's rules about: {{reason}}.",
    "GenericTypeDescription": "Your {{type}} broke Boiby's rules.",
    "GenericTypeDescriptionPlural": "One of your {{type}}s broke Boiby's rules.",
    "Appeal": "You can request an appeal or ask us to review this decision here:",
    "AppealV2": "If you think that we’ve made a mistake, you can appeal this decision here:",
    "Foreshadow": "We may give you a longer suspension - or even ban your account - if you continue breaking the rules.",
    "FollowFuture": "Please follow the rules in the future.",
    "BullyHeader": "No bullying or discrimination",
    "BullyDetail": "Boiby does not allow harassment or bullying against other users.",
    "BullyMatter": "Why does this matter?",
    "BullyImportance": "To keep our community fun for everyone, don’t use words or actions that are intended to harm or bully others. Boiby is designed to be an inclusive community.",
    "At": "at"
  },
  "Labels": {
    "Reason": "Reason:",
    "Violation": "Violation:",
    "ModeratorNote": "Moderator note:",
    "Details": "Details:",
    "ReviewDate": "Review date:",
    "DidWeMakeAMistake": "Did we make a mistake?",
    "AgreeToRules": "I agree to follow the rules",
    "AgreeToRulesV2": "I agree to know and follow the rules",
    "VideoName": "Video name:",
    "VideoID": "Video ID:",
    "Timestamp": "Timestamp:",
    "ImageName": "Image name:",
    "ImageID": "Image ID:",
    "PostID": "Post ID:",
    "Evidence": "Evidence:",
    "Trace": " ",
    "NoContent": "No content",
    "Untitled": "Untitled",
    "EntireVideo": "Entire video"
  },
  "Buttons": {
    "RequestAppeal": "Request an appeal",
    "ReportMistake": "Report a mistake",
    "Continue": "Continue",
    "Back": "Back",
    "BackV2": "Go Back",
    "ViewMore": "View more",
    "ViewLess": "View less",
    "SwitchLight": "Switch to Light",
    "SwitchDark": "Switch to Dark"
  }
}
